version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"
